### ISSUE TITLE
ImportError: Module "cumulus.storage.CumulusStaticStorage" does not define a "CumulusStaticStorage" attribute/class

### ISSUE THREAD

**Issue by weasteam** [django-cumulus/django-cumulus#197]
I get these errors when I was using collectstatic :

python manage.py collectstatic

```
/Library/Python/2.7/site-packages/robots/forms.py:7: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form RuleAdminForm needs updating
  class RuleAdminForm(forms.ModelForm):

/Library/Python/2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 42, in load_command_class
    return module.Command()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 58, in __init__
    self.storage.path('')
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/storage.py", line 391, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Library/Python/2.7/site-packages/django/core/files/storage.py", line 303, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/Library/Python/2.7/site-packages/django/utils/module_loading.py", line 33, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "/Library/Python/2.7/site-packages/django/utils/module_loading.py", line 29, in import_string
    return getattr(module, class_name)
ImportError: Module "cumulus.storage.CumulusStaticStorage" does not define a "CumulusStaticStorage" attribute/class
```

**Comment by weasteam** [comment]
I looked into the storage.py and I did not find any storage class like "CumulusStaticStorage"

As such, the bug can be fixed by changing STATICFILES_STORAGE in settings:

```
STATICFILES_STORAGE = 'cumulus.storage.SwiftclientStaticStorage'
```

**Comment by rizumu** [comment]
@weasteam is this what you are looking for? https://github.com/django-cumulus/django-cumulus/blob/31da89c23988fb6d62014247b6f036920f07efb3/cumulus/storage.py#L228

**Comment by weasteam** [comment]
@rizumu Yes. Thanks. Does this recently updated? I installed the django-cumulus around 1 week ago and I did not see the storages listed in the link.

**Comment by ferrix** [comment]
Closing an old resolved issue.
