### ISSUE TITLE
SSLError: bad handshake on fresh install

### ISSUE THREAD

**Issue by mnaglee** [django-cumulus/django-cumulus#202]
After installing cumulus per documentation, I get the following error:

```
ERROR:root:Pyrax Connect Error in `django_cumulus.cumulus.authentication.Auth`::
                           self.pyrax.set_credentials(self.username, self.api_key)

Traceback (most recent call last):
  File "/Environments/easy/local/lib/python2.7/site-packages/cumulus/authentication.py", line 51, in __init__
    self.pyrax.set_credentials(self.username, self.api_key)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/__init__.py", line 439, in _wrapped
    return fnc(*args, **kwargs)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/__init__.py", line 502, in set_credentials
    tenant_id=tenant_id, region=region, authenticate=authenticate)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/identity/rax_identity.py", line 68, in set_credentials
    region=region, tenant_id=tenant_id, authenticate=authenticate)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/base_identity.py", line 420, in set_credentials
    self.authenticate()
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/identity/rax_identity.py", line 83, in authenticate
    password=password, api_key=api_key, tenant_id=tenant_id)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/base_identity.py", line 599, in authenticate
    headers=headers, std_headers=False)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/base_identity.py", line 531, in method_post
    return self._call("POST", uri, admin, data, headers, std_headers)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/base_identity.py", line 570, in _call
    return pyrax.http.request(mthd, uri, verify=self.verify_ssl, **kwargs)
  File "/Environments/easy/local/lib/python2.7/site-packages/pyrax/http.py", line 63, in request
    resp = req_method(uri, data=data, **kwargs)
  File "/Environments/easy/local/lib/python2.7/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Environments/easy/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Environments/easy/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Environments/easy/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Environments/easy/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
```

This happens whether I install via any of the following methods:

```
pip install django-cumulus
pip install -e git://github.com/django-cumulus/django-cumulus.git#egg=django-cumulus
pip install git+git://github.com/django-cumulus/django-cumulus.git@master
```

I realize that this is more of a pyrax issue, and I've reported the problem there (https://github.com/rackspace/pyrax/issues/601), but I figured it would be worth linking to the problem (and hopefully the eventual solution) here for the sake of other users.

**Comment by thijstriemstra** [comment]
Same issue here. Even happens when running an unrelated command like `./manage.py supervisor restart all`.

**Comment by mnaglee** [comment]
@thijstriemstra found a fix, posted in the pyrax issue thread.  This isn't really a Pyrax issue at all, but rather one caused by distros packaging "older" versions of OpenSSL, and rackspace not updating their certs.  You can read the lengthy debate here:  https://github.com/certifi/python-certifi/issues/26#issuecomment-138329130

The best fix I've seen, for the time being, is to pin certifi (installed as part of requests[security], I think) to an older version.  After that point, certifi's maintainer forced a more secure model that breaks pyrax and cumulus.  You can also uninstall certifi completely, but I opted for this:

`pip uninstall -y certifi && sudo pip install certifi==2015.04.28`

I'll leave this issue open in case this assessment of the problem is incorrect.  Maintainers can close, otherwise.
